// Code generated by "stringer -type=Event"; DO NOT EDIT.

package types

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Add-0]
	_ = x[Sub-1]
	_ = x[Update-2]
	_ = x[Delete-3]
}

const _Event_name = "AddSubUpdateDelete"

var _Event_index = [...]uint8{0, 3, 6, 12, 18}

func (i Event) String() string {
	if i < 0 || i >= Event(len(_Event_index)-1) {
		return "Event(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Event_name[_Event_index[i]:_Event_index[i+1]]
}
